### ISSUE TITLE
Uploading a large dataset?

### ISSUE THREAD

**Issue by xloffree** [SelfExplainML/PiML-Toolbox#12]
Is there any way to upload a dataset of size greater than 10mb?

Thanks

**Comment by ZebinYang** [comment]
Hi @xloffree. Sure, you can upload a data larger than 10mb. This restriction is due to ipywidgets, and you may skip it by using the high code mode. For example, 

```python
import pandas as pd
data = pd.read_csv("https://archive.ics.uci.edu/ml/machine-learning-databases/00265/CASP.csv") 
exp.data_loader(data=data)
```

Also see the full example https://colab.research.google.com/github/SelfExplainML/PiML-Toolbox/blob/main/examples/Example_CustomDataLoad_Two_Ways.ipynb
