### ISSUE TITLE
Unable to figure out the Target variable for binary class ,

### ISSUE THREAD

**Issue by munchcrunch** [SelfExplainML/PiML-Toolbox#9]
I am applying PiML models to my custom data in Jupyter notebook and receiving the attached error. Please help and guid me in this regard. Thank you 

![image](https://user-images.githubusercontent.com/39892959/179293472-e357ef9c-5fce-49d6-b06a-81db1c220e5d.png)

![image](https://user-images.githubusercontent.com/39892959/179292966-d15183a2-f9ed-4624-9862-076f0fd41d98.png)

**Comment by ZebinYang** [comment]
Hi @munchcrunch, it seems that you are using the old version of PiML (0.1.4). Can you try it again using the latest version?
I can help debug if you could provide a reproducible colab notebook.

**Comment by dogefeeder** [comment]
> I am applying PiML models to my custom data in Jupyter notebook and receiving the attached error. Please help and guid me in this regard. Thank you
> 
> ![image](https://user-images.githubusercontent.com/39892959/179293472-e357ef9c-5fce-49d6-b06a-81db1c220e5d.png)
> 
> ![image](https://user-images.githubusercontent.com/39892959/179292966-d15183a2-f9ed-4624-9862-076f0fd41d98.png)

You have to set the name of the target column as 'FlagDefault'.

**Comment by ZebinYang** [comment]
@munchcrunch Can you share the data or the notebook link so that I can do some debugging? My email address is yangzb2010@connect.hku.hk

**Comment by munchcrunch** [comment]
@ZebinYang I have sent data and notebook via email. Thank you

**Comment by ZebinYang** [comment]
Hi @munchcrunch. 

This is due to we treat the last column of data as the target variable by default. If it is identified as "categorical", we will treat it as a classification problem. Here the feature "Posted Speed Limit" has 4 distinct values. Hence it is automatically treated as a multi-classification task, which is not supported yet.

Two methods can avoid this from happening. 
1. Specify the target variable, e.g., by exp.data_prepare(target="0/1"). Not sure if "0/1" is the expected target.
2. Manually change the feature type of "Posted Speed Limit" to numerical in exp.data_summary(), and then select the true target and task type in exp.data_prepare().

Thanks for pointing out this important issue, and we will improve this module in the next release soon.

**Comment by munchcrunch** [comment]
Thank you for your prompt response. It works now. I would suggest, please
fix the issue of label encoding for categorical variables, instead of
converting categorical variables into label encoding. Sometimes it
is difficult to interpret the variables with label encoding. In addition, I
would also suggest adding a solution to the multi-classification problem in
the next release. Thank you.
